name: GitHub Actions Manually
on: [workflow_dispatch]
jobs:
  e2e-tests:
    runs-on: ubuntu-latest # or macos-latest, windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install playwright dependencies
        run: npx playwright install --with-deps chromium

      - name: Install dependencies
        run: npm install

      - name: Install browsers
        run: npm i playwright-chromium

      - name: Run tests
        run: npx playwright test
